---
version: '3.5'

services:
  okbr-serenata-notebooks:
    container_name: okbr-serenata-notebooks
    image: okbr/serenata-notebooks
    networks:
      - frontend
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./notebooks/data:/home/jovyan/notebooks/data
    command:
      - "jupyter"
      - "notebook"
      - "--ip=0.0.0.0"
      - "--port=8888"
      - "--no-browser"

networks:
  frontend:
    name: okbr-serenata-notebooks
